car:
    pattern:  /
    defaults: { _controller: "NfqCarsBundle:Car:index" }

car_show:
    pattern:  /{id}/show
    defaults: { _controller: "NfqCarsBundle:Car:show" }

car_new:
    pattern:  /new
    defaults: { _controller: "NfqCarsBundle:Car:new" }

car_create:
    pattern:  /create
    defaults: { _controller: "NfqCarsBundle:Car:create" }
    requirements: { _method: post }

car_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "NfqCarsBundle:Car:edit" }

car_update:
    pattern:  /{id}/update
    defaults: { _controller: "NfqCarsBundle:Car:update" }
    requirements: { _method: post|put }

car_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "NfqCarsBundle:Car:delete" }
    requirements: { _method: post|delete }
