parameters:
#    nfq_cars.example.class: Nfq\CarsBundle\Example

services:
#    nfq_cars.example:
#        class: %nfq_cars.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
